### ISSUE TITLE
plating controls does not work

### ISSUE THREAD

**Issue by c1carpenter** [jdereus/labman#126]
VIBRIO: The value that appears does not match control description term
ZYMO MOCK: does not appear in drop down menu, and you cannot enter it. 
BLANK: cannot be entered as all caps, as indicated in the controls description, and if entered correctly from the drop down menu disappears making it seem as if it were never entered. 

Control description is not collapsing only vanishing, and it is unclear that you are supposed to be able to toggle it.

**Comment by josenavas** [comment]
I think the source of the issue here is that the class popup is not working as expected [here](https://github.com/jdereus/labman/blob/master/labman/gui/templates/plate.html#L137).

I think the solution will be to:

1. Instead of using the popup class, add a div in which those values are stored, with the prop `hidden` activated.
2. Change the wording of 'Controls description' so that it reads that you should click on it to show the error, or add some icon to accomplish that.
3. On clicking the icon/text - the div shows if it was hidden and vice-versa. Probably through writing a function `toggleControlsDescription` that should accomplish that.
4. Change the wording of the control term description:
    - VIBRIO -> vibrio.positive.control
    - BLANK -> blank
    - ZYMO MOCK -> zymo.mock ---> to make this available, it needs to be added in line 70 [here](https://github.com/jdereus/labman/blob/master/labman/db/support_files/db_patch_manual.sql) (Sorry file to big to be shown in github). Simply add , ('zymo.mock').

**Comment by josenavas** [comment]
Assigned to @wasade
