### ISSUE TITLE
Button missing in Amplicon library plates via the list function for pico green (next step)

### ISSUE THREAD

**Issue by c1carpenter** [jdereus/labman#129]

**Comment by josenavas** [comment]
To add the button for the pico green quantification, it should suffice to add this description:
```javascript
{'label': 'PicoGreen Quantification', 'urlTarget': 'process/parse_quantify'}
```
[here](https://github.com/jdereus/labman/blob/master/labman/gui/templates/plate_list.html#L13)
[here](https://github.com/jdereus/labman/blob/master/labman/gui/templates/plate_list.html#L17)
and
[here](https://github.com/jdereus/labman/blob/master/labman/gui/templates/plate_list.html#L19)

**Comment by josenavas** [comment]
Assigned to @wasade

**Comment by wasade** [comment]
I don't have enough information to understand what the specific problem is

**Comment by josenavas** [comment]
@wasade sorry for the lack of information.

The page `http://localhost:8080/plates` lists the plates. When you choose a plate of type 'Amplicon library', the list of buttons that appear under the list is missing a button that allows the user to go directly to PicoGreen quantification. The list of buttons is generated dynamically based on the values in the dictionary that I link in my previous comment.

Besides the issue described in the title, I noticed that the PicoGreen quantification page should also be available for 2 more types of plates, and hence that's why I suggested adding that entry to the dictionary (technically JS object) to those 3 items. Does that make sense?

**Comment by wasade** [comment]
Yes i think so, thank you!

**Comment by wasade** [comment]
I made the changes I think but I don't see any obvious change to the page at `http://localhost:8080/plates`. But I also don't see any buttons appear below the plates list anyway...?
<img width="1341" alt="screen shot 2018-01-26 at 3 48 57 pm" src="https://user-images.githubusercontent.com/474290/35465390-7323775a-02b0-11e8-9691-363fb9805a14.png">

**Comment by josenavas** [comment]
Thanks @wasade the buttons will appear when you select a plate using the checkbox next to the plate id.
