### ISSUE TITLE
PicoGreen Quant not pulling up amplicon plates

### ISSUE THREAD

**Issue by c1carpenter** [jdereus/labman#145]
<img width="1440" alt="screen shot 2018-01-25 at 2 36 54 pm" src="https://user-images.githubusercontent.com/35116305/35417335-ced0690c-01e1-11e8-9ae2-feec3db36398.png">

**Comment by tanaes** [comment]
Looks like this is coming from: 

```javascript

  $(document).ready(function(){
    var plateIds = {% raw plate_ids %};
    // Populate the table with the plates
    var table = $('#searchPlateTable').DataTable(
      {'ajax': {'url': '/plate_list', 'data': {'plate_type': 'gDNA'}},
       'columnDefs': [
         {'targets': -1, 'data': null,
          'render': function(data, type, row, meta){
            var plateId = data[0];
            return "<button id='addBtnPlate" + plateId + "' class='btn btn-success btn-circle-small'><span class='glyphicon glyphicon-plus'></span></button>";
          }},
         {'targets': -2,
          'render': function(data, type, row, meta){
            return data.join('<br/>');
          }},
        ]});
```

This is from line 71 in parse_quantification.html. Looks like it's querying `PlateListHandler`, which can take a list:

```python
class PlateListHandler(BaseHandler):
    @authenticated
    def get(self):
        plate_type = self.get_argument('plate_type', None)
        res = {"data": [[p['plate_id'], p['external_id'],
                         [s.title for s in Plate(p['plate_id']).studies]]
                        for p in Plate.list_plates(plate_type)]}
        self.write(res)
```

Looks like we need to pass a list via the ajax call in ` {'ajax': {'url': '/plate_list', 'data': {'plate_type': 'gDNA'}}`. Happy to do a PR with this, but not sure how to pass a list given current code. @josenavas @ElDeveloper any hints?

**Comment by josenavas** [comment]
Hi @tanaes 

Thanks for looking into this. However, `PlateListHandler` doesn't take a list as input, and the `plate_type` parameter for `Plate.list_plates` is a string not a list. To fix this issue these are the steps that need to happen:

1. Modify `Plate.list_plates` so it takes a list as a parameter, not just a string
2. Modify `PlateListHandler` so it takes a list as a parameter, since the parameter goes in the `data` element of `DataTables`, it will need to be JSON encoded/decoded.
3. Modify all ajax calls to `/plate_list` so they pass a list instead of a single string.

Thanks!!!

**Comment by josenavas** [comment]
@tanaes - In fact that function should be extended to be able to filter plates based on a property. For example, I think we should have a flag `only_quantified` that returns those plates that have been actually quantified, since that will allow us to filter the list of plates for those that have actually been quantified.

**Comment by tanaes** [comment]
Ok this is a bit bigger problem than I thought! I am busy in this meeting
right but if you don’t have a chance to get to it sooner I can try to
tackle.

**Comment by josenavas** [comment]
Thanks for confirming! I will post here if somebody starts working on it :-) let me know if you end up starting to work on this.

**Comment by josenavas** [comment]
I'm starting to work on this
