### ISSUE TITLE
Need way to create a gDNA plate without having started from plating samples

### ISSUE THREAD

**Issue by c1carpenter** [jdereus/labman#168]
Hi, 

I know some collaborators(all the Manary plates)  sent extracted gDNA plates, is there any way to start from that point?

**Comment by tanaes** [comment]
@c1carpenter, the real issue here is that the values they use for DNA extraction (and protocols) differ from ours, so we can't easily make a 'mock' DNA extraction plate that accurately replicates their approach, right?

I could envision having a checkbox on the DNA extraction page that would just render all these fields null, and perhaps add a comment field to note origin of DNA extraction?

**Comment by josenavas** [comment]
In any case we would always need a sample plate, the reason for that is because the mapping of well to samples is done at the sample plating level, not at the gdna level. That layout should exist anyways (even if we just get gdna plates) and we should just try to add a way in which the gdna protocol itself doesn't require that information - although that is highly unrecommended.

**Comment by c1carpenter** [comment]
Now that I think about it, the point of labman is so that the data can all be generated in one place, even if it was originally extracted in i.e Africa. Labman is created so you  cannot move onto the next step without having "done" the previous step. 

So in short, I agree with Jon, on rendering the fields null, but still requireing the samples to be "plated" as you mentioned Jose.

**Comment by tanaes** [comment]
@qiyunzhu @mortonjt For this issue, it will be sufficient to:

1. Add a text input box to access the `notes` property of the `Process` object, storing DNA Extraction Notes into the `notes` column of the `Process` db table. See this line: https://github.com/jdereus/labman/blob/6a34eefc3b6f280bb76cdb3da885a6c429d022e2/labman/db/process.py#L87 and this PR from @AmandaBirmingham : https://github.com/jdereus/labman/pull/221 
2. Add a check box labeled something like "DNA extracted externally" which disables the extraction-specific fields like Extraction Robots, etc. Should leave Notes, Date, and Volume enabled and required, and fill in some sort of null value in the remaining fields.
3. You can see how we disabled required input fields in our recent PR #222

**Comment by AmandaBirmingham** [comment]
Was fixed by PR #224 Adding notes and external extraction (Issue 168) but never closed.
