### ISSUE TITLE
Fixes to quantify plates interface

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#195]
Noticed some minor issues with quantification while looking at heatmaps with @ElDeveloper. Currently, you can select a plate that has already been quantified and go through all the steps of quantification without any notification that it has already been done. The uploaded values appear to be silently discarded.

I suggest the following changes to this interface:

- [ ] update logic so that you can (optionally) re-quantify a plate; for example if the first quant was bad, or done a long time ago

- [ ] update interface so that if a plate has already been quantified, the 'upload quant file' button is disabled until you click something to enable overwriting the quantification values

- [ ] update interface so that if a plate has already been quantified, OR you have just uploaded quantification values, it displays the quantification heatmap / histogram

**Comment by ElDeveloper** [comment]
I am trying to add the necessary bits to display a quantified plate as a heatmap + histogram (improvement 3), but I am having a hard time figuring out the sample names of each of the wells. Seems unclear to me how to do this as the `QuantificationProcess` doesn't exist until after the plate is saved. Are the visuals only to be displayed after the process has been saved? My intuition says that it would be useful to *see* the data before saving it, but I don't really know the process.

**Comment by tanaes** [comment]
Hmm, yes... Visualization happens pre-saving as a safeguard (or, ideally,
we'd be able to go back to a plate to visualize of course).

I think you'd have to retrieve the sample names as an array from the plate
you were going to quantify and just associate that with the same cells on
the file you read in, rather than pulling them from the
`QuantificationProcess`.

**Comment by ElDeveloper** [comment]
Thanks for the pointers @tanaes, that clears things up.

**Comment by AmandaBirmingham** [comment]
@tanaes could you please provide a sample plate reader output file that I could use while working on this issue?

**Comment by tanaes** [comment]
This should work: 10-13-17_FinRisk_33-36_library_quant.txt
<https://github.com/tanaes/metagenomics_pooling_notebook/blob/master/test_data/Quant/MiniPico/10-13-17_FinRisk_33-36_library_quant.txt>

**Comment by AmandaBirmingham** [comment]
@tanaes Assuming we are talking about the behavior of Plates > PicoGreen Quantification, let me make an important correction to the above issue description: the uploaded values are NOT discarded.  The database supports multiple quantifications for any given well/plate/etc, so every time the user chooses to save a quantification result, it goes into the database as a distinct quantification_process with its own entirely distinct set of entries in the concentration_calculation table. 

Given this, here's my input on the three proposed changes:

1) We should not need to "update logic so that you can (optionally) re-quantify a plate"--the logic to do that is already there and working.  That said, it obviously wasn't clear to the user that this functionality exists, so please suggest changes to the the interface to make the real functionality clear!
2) It is not meaningful to talk about "enabl[ing] overwriting the quantification values", as that simply can't happen.  But I do agree that it would be a good idea to let the user know in the interface if a plate has already been quantified at least once.
3) However, requiring of the interface that "if a plate has already been quantified, ..., it displays the quantification heatmap / histogram" isn't straightforward precisely because we support multiple quantifications. Say a plate has already been quantified three times--do we display just the latest quantification results in the graphics?  Or all of them?  Or should the user choose which one to display, and if so based on what information? Thoughts?

**Comment by ElDeveloper** [comment]
Sounds good, let's tackle this one 🏈
