### ISSUE TITLE
after saving extraction kit in gDNA plate extraction, there should be a drop down listing kits.

### ISSUE THREAD

**Issue by jdereus** [jdereus/labman#20]
no options are given on gdna_extraction page for extraction kits that were previously saved.

**Comment by josenavas** [comment]
Instead of a dropdown, the system is using an auto-complete. You start typing and the system will show the list of kit ids that match the search. I used this approach cause I think the list can get pretty big, which will make the interface unusable. @ghsmu414 is this an acceptable solution? AFAIK, you usually have the kit lot ids at hand.

**Comment by josenavas** [comment]
After discussing with the wet lab - the current interface works correctly.
