### ISSUE TITLE
Expose plate-level comments in sample plating and gdna extraction interfaces

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#242]
Original issue title: need to expose plate-level comments in plating interface

**Comment by AmandaBirmingham** [comment]
Greg says: need this for sample plating and gdna extraction

**Comment by ElDeveloper** [comment]
I'm working through this issue at the moment. If I understand correctly, the piece that seems to be missing is a textbox to add plate-level notes in the plating interface i.e. along with the spreadsheet, etc. And in addition, it would be useful if these notes could be displayed in the *Extract gDNA* interface.

I believe the last part is already there, for example in this plate I added notes via de Python API and those were correctly loaded when I accessed that plate:

![screen shot 2018-07-25 at 1 36 34 pm](https://user-images.githubusercontent.com/375307/43226124-c6d03202-900f-11e8-8e0b-14301ffc9e1f.png)

I want to make sure that I am understand what we are going for, because these notes we care about (for this issue) are plate-level, not sample/well-level right?

**Comment by AmandaBirmingham** [comment]
You have highlighted a key point here that we may need to discuss more.  Based on my understanding of the current code in gdna_extraction_process.GDNAExtractionProcessHandler.get, the notes collected/shown in that interface are actually NOT (despite what they appear to be) notes attached to the gDNA plate--they are notes attached to the gDNA extraction *process*.  We already have pretty good support in the code api (and a few places in the interface) for inputting notes on a process--as I recall, we added that earlier in the launch push so that users could indicate why they had to redo quantification processes, and it wasn't hard to make it a bit more generalized.

What this issue requested as written, was *plate* notes, which are supported in the database but as far as I've found not much supported yet in the code api or gui ... there is notes getter/setter on the Plate object, but notes can't be passed as part of the create call for Plate or anything.  

A really, *really* good question would be whether the need is definitely for notes on the Plate object or whether notes on the process that generated the Plate object (and that basically appear associated with the Plate object, as shown in the example you gave) would be good enough.  If process notes are good enough, our lives will be easier ...

@tanaes , since you created the issue, could you weigh in on the use case(s) driving it, so we can determine whether process notes would do?

**Comment by tanaes** [comment]
My understanding is that notes associated with the plating process are what
we want here, and indeed I think that should be a natural extension of the
generic Process.notes function. I don't see any reason to have a notes
column attached the Plates table per se -- in actuality these plates are
all being created in a process, and it's that process for which we're
wanting to record notes.

**Comment by AmandaBirmingham** [comment]
@tanaes  cool!  I think the reason that plates themselves have notes is in case there is something one needs to say about a plate that is *not* associated with any particular process, but with the persistent physical article of the plate.  For example, "This plate was discarded because we found mouse poop in it"  :)

**Comment by tanaes** [comment]
Oh interesting... I guess that begs the question of where and when one
would enter that information. 😅 But sounds good for now!

**Comment by AmandaBirmingham** [comment]
Yes, it certainly does!  As noted above, right now that field really isn't available anywhere through the gui that I can see, and has a pretty small footprint in the api.  For now, I think if one wanted to actually put in a *plate-level* comment, it would mean finding one's friendly neighborhood database admin and having them modify the notes field directly in the db.  Oh, well ... altering that is a task for another day!

**Comment by ElDeveloper** [comment]
> @ElDeveloper given @tanaes 's input that it is ok to use the notes functionality on the process level, rather than having to expose the plate-level notes, I think (hope!) this issue becomes a good deal smaller in scope.

Indeed, thanks both for the help clarifying this. I'll get back to the drawing board 👍
