### ISSUE TITLE
In plate list interfaces, should also expose date stamp

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#246]

**Comment by AmandaBirmingham** [comment]
It appears to me that the change that was made in the linked PR adds the plate creation date to the plate list page--but that is not where the users actually pick plates for use in any stage of the LabControl processes.  The actual selection of plates to use for gdna extraction, library prep, pooling, etc, happens in javascript. And that javascript is duplicated in *seven different locations* (see all the places that say `<!-- Modal to add a plate -->`).

So .. unfortunately now it is time to pay the piper.  It turns out that https://github.com/jdereus/labman/issues/351 "Centralize addPlate functionality in front-end html/javascript" is NOT a nice-to-have but a must-have to provide users with the info they need to pick between plates.  We need to centralize this functionality into one place and then add date into the columns in this plate addition modal.
