### ISSUE TITLE
Extend pool list to offer re-download of pool files for plate pools (only)

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#251]
Original issue name: add 'eyeball' to pool list to return to pooling interface to download pooling files

**Comment by tanaes** [comment]
@mortonjt

**Comment by AmandaBirmingham** [comment]
I have a work-in-progress branch going for this (see https://github.com/jdereus/labman/tree/Issue251) which produces an interface that looks like this, to match the List > Sequencing Run page: 
![screen shot 2018-07-23 at 4 45 47 pm](https://user-images.githubusercontent.com/10677935/43108769-5808492c-8e98-11e8-8ae8-7738e098da87.png)

So far so good, works like a charm ... for pools made from library plates. **HOWEVER**, the pools list page includes *all* pools, including amplicon sequencing pools.  My understanding is that amplicon sequencing pools don't have pool files generated for them because their pooling is done by hand.  Certainly the current labman code doesn't generate such files (and in fact throws an error if you try to generate a pool file for any pool that is made up of other pools).

Thus, it seems like maybe a little additional decision-making is needed here.  Should both kinds of pools display in the same list?  Assuming so, should we indicate which kind is which?  What SHOULD the user be able to see about amplicon sequencing pools after they are created, given that no pool file is available?  (Currently one can't view ANYTHING about such pools in labman once they're created, so it seems likely that some additional display is needed.)  I'd like input from someone with more wet-lab-process knowledge than me.

**Comment by AmandaBirmingham** [comment]
I spoke with Greg H. about this issue today.  He indicated that:

1) he is ok having both plate pools and sequencing pools on the same list, but he would like it to be clear which is which
2) he would like to be able to see the stored information about sequencing pools, but that this is a nice-to have
3) for soft launch, it is ok to just have no "download pool file" for sequencing pools

**Comment by AmandaBirmingham** [comment]
Fixed by merge of pull request 264
