### ISSUE TITLE
Improve "Principal Investigator" labeling on Prepare Sequencing Run page

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#295]
Users thought that "principal investigator" field would always refer to Rob, whereas it should capture the PI who is doing the study that is being sent for sequencing
Raised in amplicon walkthrough 07/30/2018

**Comment by charles-cowart** [comment]
Also, it looks like this pull-down is pulling from a list of all qiita users, instead of pulling from qiita.study_person, which is where all PI IDs from qiita.study reference to. It might help to make the list make more sense, as well as faster, to pull from this smaller table instead.

Tentatively changing to 'PI of Study Being Sent for Sequencing'. Open to alternatives.

**Comment by charles-cowart** [comment]
Tentatively changed to 'PI of study sent for sequencing:'

**Comment by charles-cowart** [comment]
It appears that the emails in qiita.study_person (unlike qiita.study_users) are not foreign-keyed to qiita.qiita_user. The pulldown menu takes a couple seconds to load; however, I'm hesitant to change it to pull from qiita.study_person, when half of the emails don't reference a qiita user, and that is the assumption the consumer of this data expects.

Text label has been changed. I will create a new issue for the slowness issue in the nice-to-haves category, and confirm with the wetlab that this user needs to be a registered qiita user.
