### ISSUE TITLE
Update well comments duplicates list in real time, not only on page reload

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#355]
While the FACT that a well contains a sample that is duplicated on another plate is updated in real time, the information on WHICH plates it is duplicated on is only updated when the sample plating page is loaded (or re-loaded).  This means the duplicate plate information is unavailable at the time of initial plating--you can only see it when you go BACK to the plate.

To reproduce:
1) Create a plate
2) Add a sample that is duplicated on other plates (for example, if using the test database, 1.SKB1.640202)
3) See that the well is colored (blue stripes) as a duplicate but the well comments box remains empty:
<img width="440" alt="screen shot 2018-10-02 at 10 49 37 am" src="https://user-images.githubusercontent.com/10677935/46367054-89a83700-c631-11e8-9d20-e9e1de514279.png">
4) Leave the sample plating page for this plate and then return to it; see that now the well comments indicate which plates sample 1.SKB1.640202 occurs on:
<img width="552" alt="screen shot 2018-10-02 at 10 50 00 am" src="https://user-images.githubusercontent.com/10677935/46367119-ac3a5000-c631-11e8-9f51-ea6395c3226a.png">
5) Modify the well in which you previously entered 1.SKB1.640202 to now hold the sample id 1.SKB2.640194
6) See that the well is colored (blue stripes) as a duplicate but the well comments are NOT updated: they still refer to sample id 1.SKB1.640202, which no longer occurs on this plate, and thus are giving the user false (outdated) information:
<img width="581" alt="screen shot 2018-10-02 at 10 50 27 am" src="https://user-images.githubusercontent.com/10677935/46367260-f6233600-c631-11e8-9dbc-f931b1dc5536.png">
7) Leave the sample plating page for this plate and then return to it; see that now the well comments correctly indicate which plates sample 1.SKB2.640194 occurs on:
<img width="520" alt="screen shot 2018-10-02 at 10 50 48 am" src="https://user-images.githubusercontent.com/10677935/46367343-1c48d600-c632-11e8-9d45-f4a28e04e9f8.png">

**Comment by antgonza** [comment]
@AmandaBirmingham, I was looking into this issue and I'm confused on what are the intended purpose of "Well comments" and the "Notes" in that page. First, I can reproduce the behavior you describe, great notes - thanks! However, I think those 2 fields are not descriptions per well but general comments/notes for the full plate. For example, if you add 2 duplicated samples or notes, the messages are not displayed per well but for the full plate AKA changing the selected wells doesn't change the messages. Thus, not sure if the issue are the names of the fields, the expected behavior, both?

See, if you add both samples & a note, leave and come back:
<img width="978" alt="Screen Shot 2019-04-09 at 5 30 37 PM" src="https://user-images.githubusercontent.com/2014559/55841676-5a491a00-5aed-11e9-891a-a4795c41063e.png">
