### ISSUE TITLE
Migrating labcontrol to latest Qiita

### ISSUE THREAD

**Issue by charles-cowart** [jdereus/labman#402]
I've discovered that the Travis build is dependent on Qiita's dev branch; this makes Travis integration a moving target, and a successful build can subsequently fail if Qiita has changed. I am currently working on updating Labcontrol to access the sample_* tables recently changed to American Gut. In addition, I've made some low-level changes to the build environment, in order to keep PostgreSQL from running out of disk space due to transaction logging.

Long term, the tests may need to be reviewed, in order to confirm that they're cleaning up after themselves; I currently don't see any tearDown() methods implemented. Near-term, Jeff has made the excellent suggestion of triggering a Travis Integration test following a Qiita integration test. In the longer term, I suggest making labcontrol either more closely bound to Qiita, or else increasing the separation through a developed API.

**Comment by josenavas** [comment]
Hi Charles,

If all the test cases in Labman are inheriting from the LabmanTestCase class (https://github.com/jdereus/labman/blob/master/labman/db/testing.py#L56), the DB is being reseted automatically after ALL tests in a class are running. Note that resetting the DB after each test is not viable due to long running times. 

Can you elaborate in which sense travis integration is a moving target? The system should work unless the changes in Qiita-dev are not backwards compatible with the tables accessed here. Note that if you don't depend on Qitta's dev branch, any needed changes in the Qiita side due to labman would not be reflected on travis until a new release is performed, creating a development blocker.

Hope this helps!

**Comment by charles-cowart** [comment]
Labcontrol was updated to use the latest Qiita schema, and PostgreSQL configuration in Travis was updated to maintain a minimal transaction log; this will prevent the Travis builds from failing due to lack of disk space. Creating a new issue out of Jeff's suggestion
