### ISSUE TITLE
Need to remove plates used for testing

### ISSUE THREAD

**Issue by charles-cowart** [jdereus/labman#439]
Provide MacKenzie a list of plates in LabControl, and let her decide which ones need to be removed or renamed. This will free up the names to be reused for the plates that should have them, as opposed to having to append something unsuitable like 'real one' or 'try 2'

**Comment by charles-cowart** [comment]
Provided list of plates to MacKenzie. Additional discussion w/ @wasade and @AmandaBirmingham

**Comment by AmandaBirmingham** [comment]
Per discussion with @charles-cowart and @wasade : discard of actual, physical plates should be very rare (see below) and the tech team anticipates that discard of purely "virtual" plates (e.g. those referenced in this issue, where a LabControl record is being discarded but no physical plate is being discarded) should ALSO be very rare after testing is complete.  

Therefore, during testing, @charles-cowart will be available to (carefully) rename discarded virtual SAMPLE plates so that wet lab can reuse their preferred names.  This is only acceptable for plates that have not been used as the basis for any downstream work.

The wet lab should be informed by @charles-cowart that we anticipate this renaming will NOT be done anymore once LabControl testing is over--so if they find that they still need this after that point, they should contact the tech team to discuss why this need continues.


From: Daniel McDonald 
Date: Wednesday, April 10, 2019 at 11:03 AM
Subject: Re: important: Re: Plate Removal

I just spoke with Greg, and it is the case that discarding is an outlier situation, which also represents physical waste, and something that he wants to discourage the wet lab from doing anyway. The situation arose because of testing, and should be rare normally — he is okay with the human policy of just not reusing names.

**Comment by charles-cowart** [comment]
Will touch base w/MacKenzie again on this issue.

**Comment by charles-cowart** [comment]
MacKenzie does not need plates removed at this time. It's useful that we had this discussion, in case this situation appears again; however, since there are no plate names to recover at this time, I will be closing the issue.
