### ISSUE TITLE
Consider merging preparation files

### ISSUE THREAD

**Issue by charles-cowart** [jdereus/labman#445]
Mapping (Preparation) files are split into two separate files, one for blanks, and the other for samples. Wetlab prefers a single mapping file for both.

**Comment by AmandaBirmingham** [comment]
... but Gail prefers that they be split into two sheets, according to the email thread archived below [emphasis mine], and as I understand it she is the primary consumer of the preparation files.  Please make sure to get her buy-in before doing any such merging.  

ALSO, keep in mind that there is not really "one [file] for blanks, and the other for samples": there is one file per study that is in the preparation, with the blanks getting treated as though they are their own study.  Thus even if blanks were shoved back into the sheet with the study they were prepped with, there is no guarantee that you would get just one prep sheet, because there can be multiple studies as part of a single prep.


From: "Birmingham, Amanda"
Date: Wednesday, October 31, 2018 at 4:16 PM
To: Gail Ackermann 
Subject: Re: Labman prep sheet names: follow-up question

> I have already started the study for blanks

Aha!  So I should NOT put all blanks from run in with each “real” study, but should instead put them into their own prep file.  Will do!
 
From: Gail Ackermann 
Date: Wednesday, October 31, 2018 at 1:54 PM
To: "Birmingham, Amanda"
Subject: Re: Labman prep sheet names: follow-up question
 
I have already started the study for blanks and it is set up in the same way as the AGP study with a prep for each run.  So all of the blanks from a single pool (no matter how many projects) are in the same prep - both pooled and not pooled.  **So Labman (or whatever moniker they choose to call it by) should output a prep for the blanks** - not sure if it should reference the study ids the actual projects are associated with the blanks. 
Hope this is helpful
Gail



On Oct 31, 2018, at 12:49 PM, Birmingham, Amanda wrote:
 
Labman actually outputs one prep sheet for each different study that is included in a run … thus, if there are two studies included in the same run, what labman produces for the “prep file” is actually a zip file that contains two separate prep sheet .txt files, one for each of the two studies.  (I will make sure that every prep file that is output contains ALL the blanks, at least until/unless you folks decide to implement the idea of creating a qiita “study” just for blanks.)
Thanks,
Amanda
 
From: Gail Ackermann 
Date: Monday, October 29, 2018 at 6:11 PM
To: "Birmingham, Amanda" 
Subject: Re: Labman prep sheet names: follow-up question
 
I am fine with the  change but what will happen when there are multiple study_ids?  Will they be concatenated and will that work for qiita?
Gail




On Oct 29, 2018, at 4:56 PM, Birmingham, Amanda wrote:
 
Hi,
When we discussed the Labman output file names on 10/09, I recorded that the desired format for the prep file name is “YYYY-mm-dd_prep_primertype (16S, ITS, 18S)_runname.txt” (e.g., “2018-10-29_prep_16S_American_Gut_Project_229_231-235.txt”).  Would you instead accept is “YYYY-mm-dd_prep_runname_studyid.txt” (e.g., “2018-10-29_prep_American_Gut_Project_229_231-235_10317.txt”)?  The reasons for the proposed change are below if you care :)  Let me know what you think.
Thanks,
Amanda
 
1.	Including a primer type (16S, 18S, ITS) is infeasible because there is no limitation in Labman that prevents a run from including amplicons done with *multiple* primer types.
2.	It is necessary to include the study id in the prep file name because Labman actually outputs one prep sheet for each different study that is included in a run.  Since there may be more than one prep sheet for the same run, the study id is needed in the prep sheet name to differentiate them from each other.

**Comment by charles-cowart** [comment]
Ah of course, thanks for the clarification! That is true, there can be multiple Studies in a preparation. My understanding based on recent meetings with Gail is that she thought it was okay for right now, but in the future it would be nice if they were merged. I will confirm, thanks!

**Comment by AmandaBirmingham** [comment]
Per discussion 20190501 with Greg, Charlie, Jeff, Gail, Daniel, Amanda: For 0.1.0 milestone, revert code to combine all studies into same prep sheet--including controls.  Then wait for greater Knight lab to figure out how to deal with controls on plates with multiple (or no) studies--get RK's live input--and then get back to us, since whatever change is implemented will have to affect some things outside LabControl.
