### ISSUE TITLE
Integrate gui tester.py into .travis.yml

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#523]

**Comment by charles-cowart** [comment]
Summary of how the javascript tests are run in Emperor:

A line in the Travis YAML file executes 'coverage run tests/all_tests.py'; Coverage is simply wrapping the execution of all_tests.py, a script with a command-line interface that can run some or all of Emperor's tests, based on parameters.

PhantomJS is a headless browser based on WebKit. A section of code in all_tests.py builds a command-line argument to execute phantomjs as console program. The argument takes runner.js and index.html as parameters.

Runner.js is a stock support script for running Qunit tests using PhantomJS as the execution engine.  Index.html declares all of the tests that need to be performed. As the tests are run through PhantomJS, information outputs to stderr and stdout. If all tests pass, the exit code for the PhantomJS process will be 0, otherwise, it will be a non-zero value.

The all_tests.py code captures the stderr, stdout and return code from the exec() of PhantomJS, potentially displays stderr and stdout, and processes the return code into a success or failure boolean in the Qunit framework.

**Comment by charles-cowart** [comment]
With the above confirmed, and headless chrome a Travis dependency, a toy version of this workflow will be forthcoming.

**Comment by wasade** [comment]
Thanks, @charles-cowart!

cc @ElDeveloper (just to keep appraised, no specific request)

**Comment by charles-cowart** [comment]
@AmandaBirmingham My pleasure!

Just an FYI to anyone interested, it seems as though the latest auto-update to Chrome causes an error when trying to run headless. Currently, I can dismiss two of the errors by specifying my own --crash_dir, but I have not been able to resolve the remaining error:

[0524/104021.267190:ERROR:browser_process_sub_thread.cc(217)] Waited 1 ms for network service

This appears to occur for others as recently as May, It doesn't appear to be resolved yet. In the meantime, I've found a source for the latest v73 build of Chromium, which doesn't have this issue:

https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/625897/

**Comment by charles-cowart** [comment]
Committing my notes to GitHub:

Testing in LabControl can be broken down into two parts: The unit-tests that are subclassed from unittest and run through nosetests, and the stress and integration tests, which are executed using db/tester.py.

All tests in gui/* are currently subclassed from unittest, specifically tornado.testing.AsyncTestCase and tornado.testing.AsyncHTTPTestCase, and use Mock where needed. They appear to test REST API endpoints. There are no unittests for javascript.

Most tests in db/* are also subclassed from unittest, specifically TestCase. The 'non-unit-tests' (stress and integration) have their own code to do things like create sample plates, etc. They call on db/* objects directly, and must be executed separately. They're executed either manually or within the Travis script by running db/tester.py.

db/tester.py is written to be a command-line utility that accepts parameters to run either some or all of the tests, but perhaps confusingly, not the unittests. No analogue for this file in gui/* currently exists.

Interestingly, both gui/ and db/ have a testing.py, but in both cases this is a root-level utility package to service multiple subclasses. Specifically:
labcontrol/gui/test/test_*.py
labcontrol/gui/handlers/process_handlers/test/test_*.py
labcontrol/gui/handlers/composition_handlers/test/test_*.py

It would perhaps be better encapsulated in the _init_.py of the directories above, but I agree that having them in a single location is more DRY. db/* is similar. IMHO the layout is confusing with testing.py named and placed where it is, but this can be refactored at a later time.

Currently there are already two executables for testing: nosetests for all python unittests, and db/tester.py for the stress and integration tests. It would be nice if all tests could be executed through a single executable with options, a la Emperor's all_tests.py.

However, for the purposes of this sprint, it appears least confusing to create an analogue for tester.py in gui/ and add an index.html and javascript tests to the existing gui/test directory. Tests confirm that python unittests and javascript unittests can coexist in gui/test and each framework will ignore the other's tests. Whether this might itself be confusing is worth discussing.

**Comment by charles-cowart** [comment]
node-qunit-puppeteer labcontrol/gui/test/index.html 10000  "--allow-file-access-from-files --no-sandbox" is already a part of travis, and should execute all Qunit tests declared in index.html and stored in a suitable location e.g.: /gui/test. Will push a wrapper py for node-qunit-puppeteer in the morning.

**Comment by charles-cowart** [comment]
Resolved by #527
